//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhishingTraining.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Enums {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Enums() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhishingTraining.Web.Resources.Enums", typeof(Enums).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linux.
        /// </summary>
        public static string ComputerOsType_Linux {
            get {
                return ResourceManager.GetString("ComputerOsType_Linux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MacOs.
        /// </summary>
        public static string ComputerOsType_MacOs {
            get {
                return ResourceManager.GetString("ComputerOsType_MacOs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string ComputerOsType_None {
            get {
                return ResourceManager.GetString("ComputerOsType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        public static string ComputerOsType_Windows {
            get {
                return ResourceManager.GetString("ComputerOsType_Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        public static string DifficultyType_Easy {
            get {
                return ResourceManager.GetString("DifficultyType_Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        public static string DifficultyType_Hard {
            get {
                return ResourceManager.GetString("DifficultyType_Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string DifficultyType_Medium {
            get {
                return ResourceManager.GetString("DifficultyType_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very easy.
        /// </summary>
        public static string DifficultyType_VeryEasy {
            get {
                return ResourceManager.GetString("DifficultyType_VeryEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very hard.
        /// </summary>
        public static string DifficultyType_VeryHard {
            get {
                return ResourceManager.GetString("DifficultyType_VeryHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link visited.
        /// </summary>
        public static string EventType_LinkVisited {
            get {
                return ResourceManager.GetString("EventType_LinkVisited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message received.
        /// </summary>
        public static string EventType_MessageReceived {
            get {
                return ResourceManager.GetString("EventType_MessageReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message sent.
        /// </summary>
        public static string EventType_MessageSent {
            get {
                return ResourceManager.GetString("EventType_MessageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string GenderType_Female {
            get {
                return ResourceManager.GetString("GenderType_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string GenderType_Male {
            get {
                return ResourceManager.GetString("GenderType_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string GenderType_Other {
            get {
                return ResourceManager.GetString("GenderType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punishment.
        /// </summary>
        public static string IncentiveType_Punishment {
            get {
                return ResourceManager.GetString("IncentiveType_Punishment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward.
        /// </summary>
        public static string IncentiveType_Reward {
            get {
                return ResourceManager.GetString("IncentiveType_Reward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android.
        /// </summary>
        public static string PhoneOsType_Android {
            get {
                return ResourceManager.GetString("PhoneOsType_Android", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blackberry.
        /// </summary>
        public static string PhoneOsType_Blackberry {
            get {
                return ResourceManager.GetString("PhoneOsType_Blackberry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iOS.
        /// </summary>
        public static string PhoneOsType_iOS {
            get {
                return ResourceManager.GetString("PhoneOsType_iOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string PhoneOsType_None {
            get {
                return ResourceManager.GetString("PhoneOsType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbian.
        /// </summary>
        public static string PhoneOsType_Symbian {
            get {
                return ResourceManager.GetString("PhoneOsType_Symbian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        public static string PhoneOsType_Windows {
            get {
                return ResourceManager.GetString("PhoneOsType_Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A1.
        /// </summary>
        public static string PhoneProviderType_A1 {
            get {
                return ResourceManager.GetString("PhoneProviderType_A1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bob.
        /// </summary>
        public static string PhoneProviderType_Bob {
            get {
                return ResourceManager.GetString("PhoneProviderType_Bob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drei.
        /// </summary>
        public static string PhoneProviderType_Drei {
            get {
                return ResourceManager.GetString("PhoneProviderType_Drei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot.
        /// </summary>
        public static string PhoneProviderType_Hot {
            get {
                return ResourceManager.GetString("PhoneProviderType_Hot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lidl Connect.
        /// </summary>
        public static string PhoneProviderType_LidlConnect {
            get {
                return ResourceManager.GetString("PhoneProviderType_LidlConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string PhoneProviderType_None {
            get {
                return ResourceManager.GetString("PhoneProviderType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S-Budget.
        /// </summary>
        public static string PhoneProviderType_SBudget {
            get {
                return ResourceManager.GetString("PhoneProviderType_SBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesss.
        /// </summary>
        public static string PhoneProviderType_Yesss {
            get {
                return ResourceManager.GetString("PhoneProviderType_Yesss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string TemplateSendType_Group {
            get {
                return ResourceManager.GetString("TemplateSendType_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual.
        /// </summary>
        public static string TemplateSendType_Individual {
            get {
                return ResourceManager.GetString("TemplateSendType_Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string TemplateType_Email {
            get {
                return ResourceManager.GetString("TemplateType_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string TemplateType_Facebook {
            get {
                return ResourceManager.GetString("TemplateType_Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram.
        /// </summary>
        public static string TemplateType_Instagram {
            get {
                return ResourceManager.GetString("TemplateType_Instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS.
        /// </summary>
        public static string TemplateType_Sms {
            get {
                return ResourceManager.GetString("TemplateType_Sms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapchat.
        /// </summary>
        public static string TemplateType_Snapchat {
            get {
                return ResourceManager.GetString("TemplateType_Snapchat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TikTok.
        /// </summary>
        public static string TemplateType_TikTok {
            get {
                return ResourceManager.GetString("TemplateType_TikTok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WhatsApp.
        /// </summary>
        public static string TemplateType_WhatsApp {
            get {
                return ResourceManager.GetString("TemplateType_WhatsApp", resourceCulture);
            }
        }
    }
}
